"""Phase 2C — Accounts Payable: vendors + non-payroll opex invoices + payments.

For each (period × cost_center × non-payroll account), generate AP invoices
that aggregate to a target opex amount. Targets are derived from:

    target_opex_period_cc = revenue_period × opex_pct × cost_center_share
    non_payroll_target    = target_opex × NON_PAYROLL_OPEX_SHARE_BY_ROLLUP[rollup]

Vendors are pre-generated by category and matched to the expense type.

This module does NOT generate payroll AP invoices — those are in payroll.py
because they share enough domain logic (FTE counts, semi-monthly cadence, SBC
accruals) to warrant a separate file.
"""
from __future__ import annotations

import uuid
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta, timezone

import numpy as np
from dateutil.relativedelta import relativedelta
from faker import Faker

from . import config as cfg
from .types import (
    APInvoiceRow,
    APPaymentRow,
    ChartOfAccountsRow,
    CostCenterRow,
    VendorRow,
)


# =============================================================================
# Calibration knobs
# =============================================================================

# Share of each opex rollup that flows through AP (vs payroll).
# Salaries & SBC are excluded; these are the residual opex categories.
NON_PAYROLL_OPEX_SHARE: dict[str, float] = {
    "cogs": 0.55,    # hosting, cloud bills, third-party services
    "sm":   0.45,    # marketing programs (digital, events, branding), T&E, tooling
    "rd":   0.30,    # cloud infra, software/tooling, contractors
    "ga":   0.50,    # legal, audit, insurance, office, software
}

# Within each rollup × cost-center function, which non-payroll accounts get
# allocated and at what relative weight. Drives which accounts get hit by AP.
# Account names match generators/entities.py exactly.
NON_PAYROLL_ACCOUNTS_BY_ROLLUP_FN: dict[tuple[str, str], dict[str, float]] = {
    # COGS — only allocated to customer_success and IT cost-centers
    ("cogs", "customer_success"): {
        "Hosting & Infrastructure": 0.55,
        "Customer Success Cost":    0.20,
        "Professional Services Cost": 0.25,
    },
    ("cogs", "it"): {
        "Hosting & Infrastructure": 0.85,
        "Customer Success Cost":    0.15,
    },
    # S&M — sales has T&E + tooling; marketing has programs + tooling
    ("sm", "sales"): {
        "Sales Travel and Entertainment": 0.55,
        "Sales Tooling":                  0.45,
    },
    ("sm", "marketing"): {
        "Marketing Programs - Digital":  0.40,
        "Marketing Programs - Events":   0.30,
        "Marketing Programs - Branding": 0.20,
        "Marketing Tooling":             0.10,
    },
    # R&D — engineering and IT spend on cloud + tooling + contractors
    ("rd", "rd"): {
        "Cloud Infrastructure - R&D":  0.40,
        "R&D Software and Tooling":    0.25,
        "R&D Contractors":             0.35,
    },
    # G&A — legal/professional, audit, office, insurance, software
    ("ga", "ga"): {
        "Legal and Professional Fees": 0.30,
        "Audit and Tax Fees":          0.10,
        "Office and Facilities":       0.20,
        "Insurance":                   0.15,
        "G&A Software and Tooling":    0.25,
    },
}

# Vendor categories per cost-center function (pool of vendors a CC's invoices
# pick from).
VENDOR_CATEGORIES_BY_FUNCTION: dict[str, list[str]] = {
    "sales":            ["saas_tool", "office"],
    "marketing":        ["marketing_agency", "saas_tool"],
    "rd":               ["cloud_infra", "saas_tool", "contractor"],
    "customer_success": ["saas_tool", "contractor"],
    "ga":               ["legal", "saas_tool", "office"],
    "it":               ["cloud_infra", "saas_tool"],
}

# Number of vendors per category to pre-generate.
VENDORS_PER_CATEGORY: dict[str, int] = {
    "cloud_infra":      6,
    "marketing_agency": 12,
    "contractor":       20,
    "saas_tool":        25,
    "legal":            8,
    "office":           10,
    "payroll_provider": 1,
}

# Invoices per (period × cost_center × account) — random within range
INVOICES_PER_CELL_RANGE = (1, 4)

# AP receipts (payments): mostly within payment_terms days. Assume NET30 default.
DEFAULT_PAYMENT_TERMS = "NET30"
PAYMENT_TERMS_DAYS = {"NET30": 30, "NET45": 45, "NET60": 60}

# Share of AP invoices that pay early/late
AP_PAYMENT_BEHAVIOR = {
    "on_time": 0.75,   # within ±5d of due_date
    "early":   0.10,   # before due_date - 5d
    "late":    0.13,   # 5-30d late
    "open":    0.02,   # still open at FY25 EOP (some payment timing variation)
}

# AP cutoff for payment generation
AP_PAYMENT_CUTOFF = cfg.fy_end(2025) + timedelta(days=14)


# =============================================================================
# Public artifacts type
# =============================================================================

@dataclass(slots=True)
class APArtifacts:
    vendors: list[VendorRow]                # all vendors (incl. payroll_provider)
    ap_invoices: list[APInvoiceRow]
    ap_payments: list[APPaymentRow]


# =============================================================================
# Helpers
# =============================================================================

def _to_dt(d: date) -> datetime:
    return datetime.combine(d, time.min, tzinfo=timezone.utc)


def _round_money(x: float) -> float:
    return round(x, 2)


def _weighted_choice(rng: np.random.Generator, choices, weights):
    total = sum(weights)
    probs = [w / total for w in weights]
    return rng.choice(choices, p=probs)


def _periods_in_window(years: list[int]):
    """Yield calendar months in fiscal-year window (Feb of (year-1) → Jan of year)."""
    start = cfg.fy_start(min(years))
    end = cfg.fy_end(max(years))
    cursor = start.replace(day=1)
    while cursor <= end:
        yield cursor, cfg.period_yyyymm(cursor)
        cursor = cursor + relativedelta(months=1)


# =============================================================================
# Step 1 — Vendors
# =============================================================================

# Mapping vendor categories to entity (most ACME vendors are US-based for procurement)
def generate_vendors(rng: np.random.Generator, faker: Faker) -> list[VendorRow]:
    vendors: list[VendorRow] = []
    payment_terms_options = ["NET30", "NET45", "NET60"]
    payment_terms_weights = [0.65, 0.25, 0.10]

    for category, count in VENDORS_PER_CATEGORY.items():
        for _ in range(count):
            # Most vendors are US; some EMEA (cloud providers from Europe etc.)
            entity = "US" if rng.random() < 0.85 else str(rng.choice(["EMEA", "APAC"], p=[0.7, 0.3]))
            name = faker.company().rstrip(", .")
            # Suffix the category to make the data self-describing
            suffix = {
                "cloud_infra":      "Cloud",
                "marketing_agency": "Agency",
                "contractor":       "Consulting",
                "saas_tool":        "Software",
                "legal":            "Legal",
                "office":           "",
                "payroll_provider": "Payroll Inc.",
            }[category]
            display = f"{name} {suffix}".strip()

            # Payroll provider has fixed name
            if category == "payroll_provider":
                display = "ACME Payroll Services Inc."

            terms = str(_weighted_choice(rng, payment_terms_options, payment_terms_weights))
            vendors.append(VendorRow(
                vendor_id=str(uuid.uuid4()),
                vendor_name=display,
                vendor_category=category,
                payment_terms=terms,
                entity_id=entity,
                created_at=_to_dt(date(2018, 1, 1) + timedelta(days=int(rng.integers(0, 365 * 6)))),
            ))
    return vendors


# =============================================================================
# Step 2 — Build target opex matrix
# =============================================================================

def _revenue_per_month(fy: int, scale: float) -> float:
    """ACME monthly revenue baseline for a fiscal year, scaled by mode."""
    annual = cfg.REVENUE_BY_FY.get(fy, 0.0) * scale
    return annual / 12.0


def _build_opex_targets(
    cost_centers: list[CostCenterRow],
    fiscal_years: list[int],
    rng: np.random.Generator,
    scale: float,
) -> dict[tuple[int, str, str], float]:
    """Returns dict (period_yyyymm, cost_center_id, pnl_rollup) -> target opex
    for the non-payroll portion only.

    Approach:
      For each (period, rollup) and entity:
        target_total_opex = monthly_revenue × opex_ratio × entity_share
      Distribute that across functions that own the rollup using the
      NON_PAYROLL_ACCOUNTS_BY_ROLLUP_FN mapping. Then split across cost centers
      within (function, entity) by HEADCOUNT_BY_FUNCTION × FUNCTION_ENTITY_WEIGHTS.
    """
    targets: dict[tuple[int, str, str], float] = defaultdict(float)

    # CC index by (function, entity)
    ccs_by_fn_entity: dict[tuple[str, str], list[str]] = defaultdict(list)
    for cc in cost_centers:
        ccs_by_fn_entity[(cc.function, cc.entity_id)].append(cc.cost_center_id)

    rollup_to_functions: dict[str, list[str]] = {
        "cogs": ["customer_success", "it"],
        "sm":   ["sales", "marketing"],
        "rd":   ["rd"],
        "ga":   ["ga"],
    }
    rollup_to_ratio: dict[str, float] = {
        "cogs": cfg.OPEX_RATIOS.cogs_pct,
        "sm":   cfg.OPEX_RATIOS.sm_pct,
        "rd":   cfg.OPEX_RATIOS.rd_pct,
        "ga":   cfg.OPEX_RATIOS.ga_pct,
    }

    for fy in fiscal_years:
        monthly_rev = _revenue_per_month(fy, scale)
        for d, period in _periods_in_window([fy]):
            for rollup, functions in rollup_to_functions.items():
                rollup_total = monthly_rev * rollup_to_ratio[rollup] * NON_PAYROLL_OPEX_SHARE[rollup]
                # Distribute across functions equally for non-COGS; COGS biased to customer_success
                if rollup == "cogs":
                    fn_weights = {"customer_success": 0.40, "it": 0.60}
                elif rollup == "sm":
                    # sales gets 30% of non-payroll S&M (T&E, tooling), marketing gets 70% (programs)
                    fn_weights = {"sales": 0.30, "marketing": 0.70}
                else:
                    fn_weights = {fn: 1.0 / len(functions) for fn in functions}

                for fn in functions:
                    fn_share = fn_weights.get(fn, 0.0)
                    if fn_share <= 0:
                        continue
                    # Distribute across entities by FUNCTION_ENTITY_WEIGHTS
                    entity_weights = cfg.FUNCTION_ENTITY_WEIGHTS[fn]
                    for entity_id, ent_w in entity_weights.items():
                        cell_target = rollup_total * fn_share * ent_w
                        cc_list = ccs_by_fn_entity.get((fn, entity_id), [])
                        if not cc_list:
                            continue
                        # Even split across cost centers in (fn, entity)
                        per_cc = cell_target / len(cc_list)
                        for cc_id in cc_list:
                            # Add some monthly noise (+/- 15%)
                            noise = float(rng.uniform(0.85, 1.15))
                            targets[(period, cc_id, rollup)] += per_cc * noise

    return targets


# =============================================================================
# Step 3 — Generate AP invoices to hit the targets
# =============================================================================

def _account_id_for_name(coa: list[ChartOfAccountsRow], name: str) -> str | None:
    for a in coa:
        if a.account_name == name:
            return a.account_id
    return None


def _account_ids_starting_with(
    coa: list[ChartOfAccountsRow], prefix: str
) -> list[str]:
    """For COGS accounts that are split per-segment (e.g. 'Hosting & Infrastructure - Sales Cloud'),
    return all matching account IDs so we can spread amounts across segments."""
    return [a.account_id for a in coa if a.account_name.startswith(prefix)]


def _vendor_pool(
    vendors: list[VendorRow], categories: list[str]
) -> list[VendorRow]:
    return [v for v in vendors if v.vendor_category in categories]


def _generate_ap_invoices(
    rng: np.random.Generator,
    coa: list[ChartOfAccountsRow],
    cost_centers: list[CostCenterRow],
    vendors: list[VendorRow],
    targets: dict[tuple[int, str, str], float],
) -> list[APInvoiceRow]:
    cc_by_id = {cc.cost_center_id: cc for cc in cost_centers}
    invoices: list[APInvoiceRow] = []
    counter = 0

    for (period, cc_id, rollup), target_amount in targets.items():
        if target_amount <= 0:
            continue
        cc = cc_by_id[cc_id]
        # Pick the account-name distribution for this (rollup, function)
        acct_dist = NON_PAYROLL_ACCOUNTS_BY_ROLLUP_FN.get((rollup, cc.function))
        if not acct_dist:
            continue
        vendor_categories = VENDOR_CATEGORIES_BY_FUNCTION.get(cc.function, [])
        vendor_pool = _vendor_pool(vendors, vendor_categories)
        if not vendor_pool:
            continue

        # For each account in dist, generate 1-3 invoices summing to its share
        for account_name, weight in acct_dist.items():
            # COGS accounts are segment-specific in the COA. If exact match
            # fails, fall back to picking a random matching account by prefix.
            account_id = _account_id_for_name(coa, account_name)
            if account_id is None:
                candidates = _account_ids_starting_with(coa, account_name)
                if not candidates:
                    continue
                account_id = candidates[int(rng.integers(0, len(candidates)))]
            account_target = target_amount * weight
            n_invoices = int(rng.integers(*INVOICES_PER_CELL_RANGE))
            # Random partition of account_target into n_invoices pieces
            cuts = sorted(rng.uniform(0, account_target, size=n_invoices - 1)) if n_invoices > 1 else []
            slices = [a - b for a, b in zip([*cuts, account_target], [0, *cuts])]
            if not slices:
                slices = [account_target]

            for slice_amount in slices:
                if slice_amount < 1.0:
                    continue
                # Random invoice date in this period
                year = period // 100
                month = period % 100
                # Days in month
                if month == 12:
                    last_day = (date(year + 1, 1, 1) - timedelta(days=1)).day
                else:
                    last_day = (date(year, month + 1, 1) - timedelta(days=1)).day
                day = int(rng.integers(1, last_day + 1))
                inv_date = date(year, month, day)

                vendor = vendor_pool[int(rng.integers(0, len(vendor_pool)))]
                terms_days = PAYMENT_TERMS_DAYS[vendor.payment_terms]
                due_date = inv_date + timedelta(days=terms_days)
                counter += 1
                invoices.append(APInvoiceRow(
                    ap_invoice_id=str(uuid.uuid4()),
                    vendor_id=vendor.vendor_id,
                    invoice_number=f"BILL-{year}-{counter:08d}",
                    invoice_date=inv_date,
                    due_date=due_date,
                    amount=_round_money(slice_amount),
                    account_id=account_id,
                    cost_center_id=cc_id,
                    status="open",
                    created_at=_to_dt(inv_date),
                ))
    return invoices


# =============================================================================
# Step 4 — Generate AP payments
# =============================================================================

def _generate_ap_payments(
    rng: np.random.Generator,
    invoices: list[APInvoiceRow],
) -> list[APPaymentRow]:
    payments: list[APPaymentRow] = []
    behaviors = list(AP_PAYMENT_BEHAVIOR.keys())
    weights = list(AP_PAYMENT_BEHAVIOR.values())

    for inv in invoices:
        behavior = str(_weighted_choice(rng, behaviors, weights))
        if behavior == "open":
            inv.status = "open"
            continue

        if behavior == "on_time":
            jitter = int(rng.integers(-5, 6))
            pay_date = inv.due_date + timedelta(days=jitter)
        elif behavior == "early":
            min_days = max(1, (inv.due_date - inv.invoice_date).days - 10)
            pay_date = inv.invoice_date + timedelta(days=int(rng.integers(1, min_days + 1)))
        else:  # late
            pay_date = inv.due_date + timedelta(days=int(rng.integers(5, 31)))

        if pay_date > AP_PAYMENT_CUTOFF:
            inv.status = "open"
            continue

        payments.append(APPaymentRow(
            ap_payment_id=str(uuid.uuid4()),
            ap_invoice_id=inv.ap_invoice_id,
            payment_date=pay_date,
            amount=inv.amount,
        ))
        inv.status = "paid"

    return payments


# =============================================================================
# Public entry point
# =============================================================================

def generate_ap(
    rng: np.random.Generator,
    faker: Faker,
    coa: list[ChartOfAccountsRow],
    cost_centers: list[CostCenterRow],
    fiscal_years: list[int],
    scale: float = 1.0,
    *,
    existing_vendors: list[VendorRow] | None = None,
) -> APArtifacts:
    """Generate AP non-payroll opex.

    `scale` should match the GenerationMode customer_scale (1.0 for full,
    0.10 for quick) so AP target opex is consistent with CRM revenue volume.

    `existing_vendors` lets payroll.py share the vendor list (in case it has
    already created the payroll_provider vendor). If None, vendors are created
    here.
    """
    if existing_vendors is None:
        vendors = generate_vendors(rng, faker)
    else:
        vendors = existing_vendors

    targets = _build_opex_targets(cost_centers, fiscal_years, rng, scale)
    invoices = _generate_ap_invoices(rng, coa, cost_centers, vendors, targets)
    payments = _generate_ap_payments(rng, invoices)

    return APArtifacts(
        vendors=vendors,
        ap_invoices=invoices,
        ap_payments=payments,
    )
