import { useState } from 'react'
import { BookOpen, Download, CheckCircle2, Loader2 } from 'lucide-react'

const SECTIONS = [
  { icon: '📊', label: 'P&L Summary', desc: 'Revenue, gross margin, and operating income by quarter' },
  { icon: '📈', label: 'ARR Waterfall', desc: 'Net new ARR breakdown by movement type' },
  { icon: '💰', label: 'AR Aging Analysis', desc: 'Outstanding receivables by bucket and customer' },
  { icon: '🤖', label: 'AI Commentary', desc: 'Executive narrative generated by Claude Sonnet' },
  { icon: '🔮', label: 'Forward Guidance', desc: '4-quarter revenue and margin forecast' },
]

type Status = 'idle' | 'loading' | 'success' | 'error'

export default function BoardPack() {
  const [status, setStatus] = useState<Status>('idle')
  const [errorMsg, setErrorMsg] = useState('')

  async function handleGenerate() {
    setStatus('loading')
    setErrorMsg('')
    try {
      const res = await fetch('http://localhost:8000/board-pack', { method: 'POST' })
      if (!res.ok) throw new Error(`Server responded ${res.status}: ${res.statusText}`)

      // Attempt file download
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `ACME-Finance-Board-Pack-${new Date().toISOString().slice(0, 7)}.pdf`
      a.click()
      URL.revokeObjectURL(url)
      setStatus('success')
    } catch (e) {
      setErrorMsg(String(e))
      setStatus('error')
    }
  }

  return (
    <div className="px-8 py-7 max-w-screen-xl mx-auto">
      <div className="mb-6">
        <h1 className="text-[15px] font-semibold text-atlas-ink mb-1">Board Pack</h1>
        <p className="text-[12px] text-atlas-inkDim">Generate a comprehensive PDF board report for the latest period</p>
      </div>

      <div className="grid grid-cols-[1fr_380px] gap-6 items-start">
        {/* Left — sections list */}
        <div className="bg-atlas-card rounded-2xl border border-atlas-rule p-6">
          <div className="flex items-center gap-2 mb-5">
            <BookOpen size={14} className="text-atlas-brand" />
            <span className="text-[13px] font-semibold text-atlas-ink">What's Included</span>
          </div>
          <div className="space-y-3">
            {SECTIONS.map(s => (
              <div key={s.label} className="flex items-start gap-3 p-3 rounded-xl bg-atlas-bg border border-atlas-rule">
                <span className="text-xl flex-shrink-0 mt-0.5">{s.icon}</span>
                <div>
                  <p className="text-[13px] font-medium text-atlas-ink">{s.label}</p>
                  <p className="text-[12px] text-atlas-inkDim mt-0.5">{s.desc}</p>
                </div>
                <CheckCircle2 size={14} className="text-atlas-ok flex-shrink-0 mt-1 ml-auto" />
              </div>
            ))}
          </div>
          <div className="mt-5 pt-4 border-t border-atlas-rule">
            <p className="text-[11.5px] text-atlas-inkMute leading-relaxed">
              The board pack is generated as a PDF document using live data from the ACME Finance data warehouse.
              AI commentary is written by Claude Sonnet and reviewed against the underlying metrics.
            </p>
          </div>
        </div>

        {/* Right — action card */}
        <div className="bg-atlas-card rounded-2xl border border-atlas-rule p-6 sticky top-6">
          <div
            className="w-12 h-12 rounded-2xl flex items-center justify-center mb-4"
            style={{ background: 'linear-gradient(135deg, #0b66e4, #6c4ad9)' }}
          >
            <BookOpen size={22} className="text-white" />
          </div>

          <h2 className="text-[15px] font-semibold text-atlas-ink mb-1">Generate Board Pack PDF</h2>
          <p className="text-[12.5px] text-atlas-inkDim mb-5 leading-relaxed">
            Creates a PDF with all sections listed. Generation typically takes 15–30 seconds.
            The file will download automatically when ready.
          </p>

          {status === 'error' && (
            <div className="bg-atlas-redSoft border border-atlas-red/20 rounded-xl px-3 py-2.5 text-[12px] text-atlas-red mb-4">
              {errorMsg}
            </div>
          )}

          {status === 'success' && (
            <div className="bg-atlas-okSoft border border-atlas-ok/20 rounded-xl px-3 py-2.5 text-[12px] text-atlas-ok mb-4 flex items-center gap-2">
              <CheckCircle2 size={13} />
              Board pack downloaded successfully!
            </div>
          )}

          <button
            onClick={handleGenerate}
            disabled={status === 'loading'}
            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-atlas-brand hover:bg-atlas-brandDeep disabled:opacity-60 disabled:cursor-not-allowed text-white text-[13px] font-medium rounded-xl transition-colors"
          >
            {status === 'loading' ? (
              <>
                <Loader2 size={14} className="animate-spin" />
                Generating PDF…
              </>
            ) : (
              <>
                <Download size={14} />
                Generate & Download PDF
              </>
            )}
          </button>

          <div className="mt-4 grid grid-cols-2 gap-2 text-[11px] text-atlas-inkMute">
            <div className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-atlas-ok" />
              Live data
            </div>
            <div className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-atlas-brand" />
              AI commentary
            </div>
            <div className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-atlas-violet" />
              5-page PDF
            </div>
            <div className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-atlas-warn" />
              Board-ready
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
