import { useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { generateCommentary } from '../api/client'
import { FileText, Sparkles } from 'lucide-react'

const PERIODS = [
  { label: 'Jan 2024', value: '202401' },
  { label: 'Feb 2024', value: '202402' },
  { label: 'Mar 2024', value: '202403' },
  { label: 'Apr 2024', value: '202404' },
  { label: 'May 2024', value: '202405' },
  { label: 'Jun 2024', value: '202406' },
  { label: 'Jul 2024', value: '202407' },
  { label: 'Aug 2024', value: '202408' },
  { label: 'Sep 2024', value: '202409' },
  { label: 'Oct 2024', value: '202410' },
  { label: 'Nov 2024', value: '202411' },
  { label: 'Dec 2024', value: '202412' },
]

const ENTITIES = ['All', 'US', 'EMEA', 'APAC']

function SkeletonBlock() {
  return (
    <div className="space-y-3 animate-pulse">
      {[100, 92, 84, 78, 96, 70, 88, 60].map((w, i) => (
        <div key={i} className="h-3.5 bg-atlas-bgSunken rounded-full" style={{ width: `${w}%` }} />
      ))}
      <div className="h-4" />
      {[88, 94, 76, 82, 90].map((w, i) => (
        <div key={i + 8} className="h-3.5 bg-atlas-bgSunken rounded-full" style={{ width: `${w}%` }} />
      ))}
    </div>
  )
}

export default function Commentary() {
  const [period, setPeriod] = useState('202412')
  const [entity, setEntity] = useState('All')
  const [result, setResult] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [hasGenerated, setHasGenerated] = useState(false)

  async function handleGenerate() {
    setLoading(true)
    setError(null)
    setResult('')
    setHasGenerated(true)
    try {
      const text = await generateCommentary(period, entity === 'All' ? undefined : entity)
      setResult(text)
    } catch (e) {
      setError(String(e))
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="px-8 py-7 max-w-screen-xl mx-auto">
      <div className="mb-6">
        <h1 className="text-[15px] font-semibold text-atlas-ink mb-1">AI Commentary</h1>
        <p className="text-[12px] text-atlas-inkDim">Generate AI-powered narrative commentary for any period</p>
      </div>

      <div className="grid grid-cols-[300px_1fr] gap-6 items-start">
        {/* Left panel — form */}
        <div className="bg-atlas-card rounded-2xl border border-atlas-rule p-5 sticky top-6">
          <div className="flex items-center gap-2 mb-4">
            <FileText size={14} className="text-atlas-brand" />
            <span className="text-[13px] font-semibold text-atlas-ink">Generate Commentary</span>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-[11.5px] font-medium text-atlas-inkDim mb-1.5">Period</label>
              <select
                value={period}
                onChange={e => setPeriod(e.target.value)}
                className="w-full bg-atlas-bg border border-atlas-rule rounded-lg px-3 py-2 text-[13px] text-atlas-ink outline-none focus:border-atlas-brand focus:ring-1 focus:ring-atlas-brand/20 transition-all"
              >
                {PERIODS.map(p => (
                  <option key={p.value} value={p.value}>{p.label}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-[11.5px] font-medium text-atlas-inkDim mb-1.5">Entity</label>
              <select
                value={entity}
                onChange={e => setEntity(e.target.value)}
                className="w-full bg-atlas-bg border border-atlas-rule rounded-lg px-3 py-2 text-[13px] text-atlas-ink outline-none focus:border-atlas-brand focus:ring-1 focus:ring-atlas-brand/20 transition-all"
              >
                {ENTITIES.map(e => (
                  <option key={e} value={e}>{e}</option>
                ))}
              </select>
            </div>

            <button
              onClick={handleGenerate}
              disabled={loading}
              className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-atlas-brand hover:bg-atlas-brandDeep disabled:opacity-50 disabled:cursor-not-allowed text-white text-[13px] font-medium rounded-xl transition-colors"
            >
              <Sparkles size={13} />
              {loading ? 'Generating…' : 'Generate Commentary'}
            </button>
          </div>

          <div className="mt-5 pt-4 border-t border-atlas-rule">
            <p className="text-[11px] text-atlas-inkMute leading-relaxed">
              Commentary is generated by Claude Sonnet using P&L, ARR, and AR data for the selected period.
            </p>
          </div>
        </div>

        {/* Right panel — output */}
        <div className="bg-atlas-card rounded-2xl border border-atlas-rule p-6 min-h-[480px]">
          {!hasGenerated && !loading && (
            <div className="flex flex-col items-center justify-center h-64 gap-3 text-center">
              <div
                className="w-10 h-10 rounded-xl flex items-center justify-center"
                style={{ background: 'linear-gradient(135deg, #0b66e4, #6c4ad9)' }}
              >
                <Sparkles size={18} className="text-white" />
              </div>
              <p className="text-[13px] font-medium text-atlas-ink">Select a period and generate</p>
              <p className="text-[12px] text-atlas-inkDim max-w-xs">
                AI will analyze the financial data and write a narrative commentary with key insights.
              </p>
            </div>
          )}

          {loading && <SkeletonBlock />}

          {error && (
            <div className="bg-atlas-redSoft border border-atlas-red/20 rounded-xl px-4 py-3 text-[13px] text-atlas-red">
              {error}
            </div>
          )}

          {result && !loading && (
            <div className="prose prose-sm max-w-none prose-headings:text-atlas-ink prose-headings:font-semibold prose-p:text-atlas-inkSoft prose-strong:text-atlas-ink prose-table:text-[12px]">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>
                {result}
              </ReactMarkdown>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
